// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"context"
	"time"

	"github.com/vorzela/vorm/query"
)

// Comment maps the "comments" table.
type Comment struct {
	ID        int64     `json:"id" db:"id"`
	PostID    int64     `json:"post_id" db:"post_id"`
	Body      *string   `json:"body,omitempty" db:"body"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`

	// Relations — populated by .With(...); never selected or written.
	Post *Post `json:"post,omitempty" db:"-"`
}

// CommentTable is the table name for Comment.
const CommentTable = "comments"

// CommentColumns gives compile-time-checked column names.
var CommentColumns = struct {
	ID        string
	PostID    string
	Body      string
	CreatedAt string
}{
	ID:        "id",
	PostID:    "post_id",
	Body:      "body",
	CreatedAt: "created_at",
}

// CommentColumnList is the explicit projection vorm selects; wildcards are never emitted.
var CommentColumnList = []string{"id", "post_id", "body", "created_at"}

// Comments is the typed query entrypoint for "comments".
var Comments = query.Model[Comment](query.Meta{
	Table:       CommentTable,
	Columns:     CommentColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
	Indexes:     CommentIndexes,
})

// CommentIndexes mirrors the indexes that exist on "comments".
var CommentIndexes = []query.IndexInfo{
	{Name: "comments_pkey", Columns: []string{"id"}, Unique: true, Primary: true, Method: "btree"},
	{Name: "comments_post_id_idx", Columns: []string{"post_id"}, Unique: false, Primary: false, Method: "btree"},
}

// Relations are registered on package init so .With("name") resolves without
// extra wiring. Every loader batches the whole result set into a bounded
// number of queries — there is no per-row lookup.
func init() {
	query.RegisterRelation(query.Relation{
		Name: "post", Kind: query.RelationBelongsTo, Table: "posts", Field: "Post",
		LocalKey: "post_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*Comment) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[Comment, Post]{
			Related:   Posts,
			OwnerKey:  "id",
			ParentKey: func(m *Comment) any { return m.PostID },
			ChildKey:  func(r *Post) any { return r.ID },
			Assign:    func(m *Comment, r *Post) { m.Post = r },
		})
	})

}
