// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"context"

	"github.com/vorzela/vorm/query"
)

// UserPostCount calls the database function user_post_count.
func UserPostCount(ctx context.Context, db query.DB, uid int64) (int64, error) {
	const stmt = `SELECT "user_post_count"($1)`
	var out int64
	err := db.QueryRowContext(ctx, stmt, uid).Scan(&out)
	return out, err
}

// RefreshStats calls the database routine refresh_stats.
func RefreshStats(ctx context.Context, db query.DB) error {
	const stmt = `SELECT "refresh_stats"()`
	_, err := db.ExecContext(ctx, stmt)
	return err
}

// ActiveUserIDs calls the set-returning database function active_user_ids.
func ActiveUserIDs(ctx context.Context, db query.DB, minId int64) ([]int64, error) {
	const stmt = `SELECT v FROM "active_user_ids"($1) AS t(v)`
	rows, err := db.QueryContext(ctx, stmt, minId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []int64
	for rows.Next() {
		var v int64
		if err := rows.Scan(&v); err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

// Not generated (signature has no direct Go form):
//   - audit_trigger: returns trigger
