// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"context"
	"time"

	"github.com/vorzela/vorm/query"
)

// PostTag maps the "post_tags" table.
type PostTag struct {
	ID        int64     `json:"id" db:"id"`
	PostID    int64     `json:"post_id" db:"post_id"`
	TagID     int64     `json:"tag_id" db:"tag_id"`
	Pinned    bool      `json:"pinned" db:"pinned"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`

	// Relations — populated by .With(...); never selected or written.
	Post *Post `json:"post,omitempty" db:"-"`
	Tag  *Tag  `json:"tag,omitempty" db:"-"`
}

// PostTagTable is the table name for PostTag.
const PostTagTable = "post_tags"

// PostTagColumns gives compile-time-checked column names.
var PostTagColumns = struct {
	ID        string
	PostID    string
	TagID     string
	Pinned    string
	CreatedAt string
}{
	ID:        "id",
	PostID:    "post_id",
	TagID:     "tag_id",
	Pinned:    "pinned",
	CreatedAt: "created_at",
}

// PostTagColumnList is the explicit projection vorm selects; wildcards are never emitted.
var PostTagColumnList = []string{"id", "post_id", "tag_id", "pinned", "created_at"}

// PostTags is the typed query entrypoint for "post_tags".
var PostTags = query.Model[PostTag](query.Meta{
	Table:       PostTagTable,
	Columns:     PostTagColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
	Indexes:     PostTagIndexes,
})

// PostTagIndexes mirrors the indexes that exist on "post_tags".
var PostTagIndexes = []query.IndexInfo{
	{Name: "post_tags_pkey", Columns: []string{"id"}, Unique: true, Primary: true, Method: "btree"},
	{Name: "post_tags_post_id_tag_id_key", Columns: []string{"post_id", "tag_id"}, Unique: true, Primary: false, Method: "btree"},
}

// Relations are registered on package init so .With("name") resolves without
// extra wiring. Every loader batches the whole result set into a bounded
// number of queries — there is no per-row lookup.
func init() {
	query.RegisterRelation(query.Relation{
		Name: "post", Kind: query.RelationBelongsTo, Table: "posts", Field: "Post",
		LocalKey: "post_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*PostTag) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[PostTag, Post]{
			Related:   Posts,
			OwnerKey:  "id",
			ParentKey: func(m *PostTag) any { return m.PostID },
			ChildKey:  func(r *Post) any { return r.ID },
			Assign:    func(m *PostTag, r *Post) { m.Post = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "tag", Kind: query.RelationBelongsTo, Table: "tags", Field: "Tag",
		LocalKey: "tag_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*PostTag) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[PostTag, Tag]{
			Related:   Tags,
			OwnerKey:  "id",
			ParentKey: func(m *PostTag) any { return m.TagID },
			ChildKey:  func(r *Tag) any { return r.ID },
			Assign:    func(m *PostTag, r *Tag) { m.Tag = r },
		})
	})

}
