// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"context"
	"encoding/json"
	"time"

	"github.com/vorzela/vorm/query"
)

// Post maps the "posts" table.
type Post struct {
	ID        int64           `json:"id" db:"id"`
	AuthorID  int64           `json:"author_id" db:"author_id"`
	EditorID  *int64          `json:"editor_id,omitempty" db:"editor_id"`
	Title     string          `json:"title" db:"title"`
	State     PostState       `json:"state" db:"state"`
	Body      *string         `json:"body,omitempty" db:"body"`
	Metadata  json.RawMessage `json:"metadata,omitempty" db:"metadata"`
	CreatedAt time.Time       `json:"created_at" db:"created_at"`

	// Relations — populated by .With(...); never selected or written.
	Author         *User     `json:"author,omitempty" db:"-"`
	Comments       []Comment `json:"comments,omitempty" db:"-"`
	CommentsCount  int64     `json:"comments_count" db:"comments_count"`
	CommentsExists bool      `json:"comments_exists" db:"comments_exists"`
	Editor         *User     `json:"editor,omitempty" db:"-"`
	LatestComment  *Comment  `json:"latest_comment,omitempty" db:"-"`
	OldestComment  *Comment  `json:"oldest_comment,omitempty" db:"-"`
	Tags           []Tag     `json:"tags,omitempty" db:"-"`
	TagsCount      int64     `json:"tags_count" db:"tags_count"`
	TagsExists     bool      `json:"tags_exists" db:"tags_exists"`
}

// PostTable is the table name for Post.
const PostTable = "posts"

// PostColumns gives compile-time-checked column names.
var PostColumns = struct {
	ID        string
	AuthorID  string
	EditorID  string
	Title     string
	State     string
	Body      string
	Metadata  string
	CreatedAt string
}{
	ID:        "id",
	AuthorID:  "author_id",
	EditorID:  "editor_id",
	Title:     "title",
	State:     "state",
	Body:      "body",
	Metadata:  "metadata",
	CreatedAt: "created_at",
}

// PostColumnList is the explicit projection vorm selects; wildcards are never emitted.
var PostColumnList = []string{"id", "author_id", "editor_id", "title", "state", "body", "metadata", "created_at"}

// Posts is the typed query entrypoint for "posts".
var Posts = query.Model[Post](query.Meta{
	Table:       PostTable,
	Columns:     PostColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
	Indexes:     PostIndexes,
})

// PostIndexes mirrors the indexes that exist on "posts".
var PostIndexes = []query.IndexInfo{
	{Name: "posts_pkey", Columns: []string{"id"}, Unique: true, Primary: true, Method: "btree"},
	{Name: "posts_author_id_idx", Columns: []string{"author_id"}, Unique: false, Primary: false, Method: "btree"},
}

// Relations are registered on package init so .With("name") resolves without
// extra wiring. Every loader batches the whole result set into a bounded
// number of queries — there is no per-row lookup.
func init() {
	query.RegisterRelation(query.Relation{
		Name: "author", Kind: query.RelationBelongsTo, Table: "users", Field: "Author",
		LocalKey: "author_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[Post, User]{
			Related:   Users,
			OwnerKey:  "id",
			ParentKey: func(m *Post) any { return m.AuthorID },
			ChildKey:  func(r *User) any { return r.ID },
			Assign:    func(m *Post, r *User) { m.Author = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "comments", Kind: query.RelationHasMany, Table: "comments", Field: "Comments",
		LocalKey: "id", ForeignKey: "post_id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadHasMany(ctx, db, rows, query.HasMany[Post, Comment]{
			Related:    Comments,
			ForeignKey: "post_id",
			ParentKey:  func(m *Post) any { return m.ID },
			ChildKey:   func(r *Comment) any { return r.PostID },
			Assign:     func(m *Post, rows []Comment) { m.Comments = rows },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "editor", Kind: query.RelationBelongsTo, Table: "users", Field: "Editor",
		LocalKey: "editor_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[Post, User]{
			Related:   Users,
			OwnerKey:  "id",
			ParentKey: func(m *Post) any { return m.EditorID },
			ChildKey:  func(r *User) any { return r.ID },
			Assign:    func(m *Post, r *User) { m.Editor = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "latest_comment", Kind: query.RelationHasOneOfMany, Table: "comments", Field: "LatestComment",
		LocalKey: "id", ForeignKey: "post_id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadHasOneOfMany(ctx, db, rows, query.HasOneOfMany[Post, Comment]{
			Related:    Comments,
			ForeignKey: "post_id",
			OrderCol:   "created_at",
			Desc:       true,
			ParentKey:  func(m *Post) any { return m.ID },
			ChildKey:   func(r *Comment) any { return r.PostID },
			Assign:     func(m *Post, r *Comment) { m.LatestComment = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "oldest_comment", Kind: query.RelationHasOneOfMany, Table: "comments", Field: "OldestComment",
		LocalKey: "id", ForeignKey: "post_id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadHasOneOfMany(ctx, db, rows, query.HasOneOfMany[Post, Comment]{
			Related:    Comments,
			ForeignKey: "post_id",
			OrderCol:   "created_at",
			Desc:       false,
			ParentKey:  func(m *Post) any { return m.ID },
			ChildKey:   func(r *Comment) any { return r.PostID },
			Assign:     func(m *Post, r *Comment) { m.OldestComment = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "tags", Kind: query.RelationBelongsToMany, Table: "tags", Field: "Tags",
		LocalKey: "id", ForeignKey: "",
		PivotTable: "post_tags", PivotLocalKey: "post_id", PivotForeignKey: "tag_id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadBelongsToMany(ctx, db, rows, query.BelongsToMany[Post, Tag]{
			Related:         Tags,
			PivotTable:      "post_tags",
			PivotParentKey:  "post_id",
			PivotRelatedKey: "tag_id",
			RelatedKey:      "id",
			ParentKey:       func(m *Post) any { return m.ID },
			ChildKey:        func(r *Tag) any { return r.ID },
			Assign:          func(m *Post, rows []Tag) { m.Tags = rows },
		})
	})

}

// TagsRelation is the belongs-to-many association (Attach/Detach/Sync/Toggle).
// The eager-load field is named Tags; Go cannot share that identifier with a method.
func (m *Post) TagsRelation() query.BelongsToManyAssoc {
	return query.BelongsToManyAssoc{
		PivotTable: "post_tags", PivotParentKey: "post_id", PivotRelatedKey: "tag_id",
		ParentID: m.ID, CreatedAt: true, UpdatedAt: false, UniquePair: true,
	}
}

func (m *Post) AttachTags(ctx context.Context, db query.DB, ids ...any) error {
	return m.TagsRelation().Attach(ctx, db, ids...)
}

func (m *Post) DetachTags(ctx context.Context, db query.DB, ids ...any) error {
	return m.TagsRelation().Detach(ctx, db, ids...)
}

func (m *Post) SyncTags(ctx context.Context, db query.DB, ids ...any) error {
	return m.TagsRelation().Sync(ctx, db, ids...)
}

func (m *Post) ToggleTags(ctx context.Context, db query.DB, ids ...any) error {
	return m.TagsRelation().Toggle(ctx, db, ids...)
}
