// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"time"

	"github.com/vorzela/vorm/query"
)

// Place maps the "places" table.
type Place struct {
	ID       int64  `json:"id" db:"id"`
	Name     string `json:"name" db:"name"`
	Location string `json:"location" db:"location"`
	// default CURRENT_TIMESTAMP
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	// default CURRENT_TIMESTAMP
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// PlaceTable is the table name for Place.
const PlaceTable = "places"

// PlaceColumns gives compile-time-checked column names.
var PlaceColumns = struct {
	ID        string
	Name      string
	Location  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	Location:  "location",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// PlaceColumnList is the explicit projection vorm selects; wildcards are never emitted.
var PlaceColumnList = []string{"id", "name", "location", "created_at", "updated_at"}

// Places is the typed query entrypoint for "places".
var Places = query.Model[Place](query.Meta{
	Table:       PlaceTable,
	Columns:     PlaceColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
	Indexes:     PlaceIndexes,
})

// PlaceIndexes mirrors the indexes that exist on "places".
var PlaceIndexes = []query.IndexInfo{
	{Name: "places_location_gix", Columns: []string{"location"}, Unique: false, Primary: false, Method: "gist"},
	{Name: "places_pkey", Columns: []string{"id"}, Unique: true, Primary: true, Method: "btree"},
}
